# Generated by Django 3.1.1 on 2020-11-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_author_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_name',
        ),
    ]
